version: '3.4'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  vuesigninform:
    image: vuesigninform
    build:
      context: Client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173

  server:
    image: server
    build:
      context: Server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
